// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PwcApi.Data;

#nullable disable

namespace PwcApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PwcApi.Models.ParentsEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingCity")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingPincode")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingState")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ChildDOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChildName")
                        .HasColumnType("longtext");

                    b.Property<string>("ChildSchoolCity")
                        .HasColumnType("longtext");

                    b.Property<string>("ChildSchoolName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DiscountCode")
                        .HasColumnType("longtext");

                    b.Property<int?>("MediaConsent")
                        .HasColumnType("int");

                    b.Property<string>("ParentEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ParentName")
                        .HasColumnType("longtext");

                    b.Property<string>("ParentPhone")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolId")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionAgeGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionDays")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionFrequency")
                        .HasColumnType("longtext");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("SessionName")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionTimeSlot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ParentEnrollments");
                });

            modelBuilder.Entity("PwcApi.Models.PotentialParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChildSchoolName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Child_DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Child_Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MediaConsent")
                        .HasColumnType("int");

                    b.Property<string>("Parent_Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Parent_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Parent_Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("School_City")
                        .HasColumnType("longtext");

                    b.Property<string>("School_Email")
                        .HasColumnType("longtext");

                    b.Property<string>("School_Location")
                        .HasColumnType("longtext");

                    b.Property<string>("School_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("School_Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Potential_Parents");
                });

            modelBuilder.Entity("PwcApi.Models.ResourceAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckInImage")
                        .HasColumnType("longtext");

                    b.Property<string>("CheckInLocation")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("CheckOutImage")
                        .HasColumnType("longtext");

                    b.Property<string>("CheckOutLocation")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCalls")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmails")
                        .HasColumnType("int");

                    b.Property<int>("TotalParentsTargeted")
                        .HasColumnType("int");

                    b.Property<int>("TotalWhatsApp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResourceAttendances");
                });

            modelBuilder.Entity("PwcApi.Models.ResourceMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ResourceMasters");
                });

            modelBuilder.Entity("PwcApi.Models.SchoolMaster", b =>
                {
                    b.Property<string>("SchoolId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActivityCount")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPersonEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPersonPhone")
                        .HasColumnType("longtext");

                    b.Property<int?>("CounselorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FacilitationCharges")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("IsEnrolled")
                        .HasColumnType("int");

                    b.Property<int?>("OnBoardingId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerName")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("Plan")
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipalEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipalName")
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipalPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("PromoCode")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PromoDiscount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SalesPersonId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolCity")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolCountry")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolName")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolPincode")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolState")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact1Email")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact1Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact1Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact1Position")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact2Email")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact2Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact2Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact2Position")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact3Email")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact3Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact3Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact3Position")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact4Email")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact4Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact4Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionContact4Position")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("longtext");

                    b.HasKey("SchoolId");

                    b.ToTable("SchoolMaster");
                });

            modelBuilder.Entity("PwcApi.Models.SessionMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CoachId")
                        .HasColumnType("longtext");

                    b.Property<string>("CoachName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("SchoolId")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SessionMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
